### ISSUE TITLE
Random Score error

### ISSUE THREAD

**Issue by dabster** [elastic/elasticsearch-net#1559]
Hello,

I was trying to something similar to this example:

https://www.elastic.co/guide/en/elasticsearch/guide/current/random-scoring.html

With a query that looks like this:

                     .Query(mq => mq
                                    .FunctionScore(cfs => cfs
                                        .Filter(fsf => fsf.GeoDistance(p => p.Location, d => d.Distance(distanceKm, GeoUnit.Kilometers).Location(latitude, longitude)))
                                        .RandomScore()
                                        .Functions(func => func
                                                    .Weight(5).Filter(f => f.GeoDistanceRange(p => p.Location, d => d.Distance(0, 5, GeoUnit.Kilometers).Location(latitude, longitude))),
                                                func => func
                                                    .Weight(4).Filter(f => f.GeoDistanceRange(p => p.Location, d => d.Distance(5, 10, GeoUnit.Kilometers).Location(latitude, longitude))),
                                                func => func
                                                    .Weight(3).Filter(f => f.GeoDistanceRange(p => p.Location, d => d.Distance(10, 15, GeoUnit.Kilometers).Location(latitude, longitude))),
                                                func => func
                                                    .Weight(2).Filter(f => f.GeoDistanceRange(p => p.Location, d => d.Distance(15, 20, GeoUnit.Kilometers).Location(latitude, longitude))),
                                                func => func
                                                    .Weight(1).Filter(f => f.GeoDistanceRange(p => p.Location, d => d.Distance(20, 1000, GeoUnit.Kilometers).Location(latitude, longitude)))
                                                )))

The output is this:
```
  "query": {
    "function_score": {
      "functions": [
        {
          "weight": 5.0,
          "filter": {
            "geo_distance_range": {
              "location": "43.653473, -79.388692",
              "from": 0.0,
              "to": 5.0,
              "unit": "km"
            }
          }
        },
        {
          "weight": 4.0,
          "filter": {
            "geo_distance_range": {
              "location": "43.653473, -79.388692",
              "from": 5.0,
              "to": 10.0,
              "unit": "km"
            }
          }
        },
        {
          "weight": 3.0,
          "filter": {
            "geo_distance_range": {
              "location": "43.653473, -79.388692",
              "from": 10.0,
              "to": 15.0,
              "unit": "km"
            }
          }
        },
        {
          "weight": 2.0,
          "filter": {
            "geo_distance_range": {
              "location": "43.653473, -79.388692",
              "from": 15.0,
              "to": 20.0,
              "unit": "km"
            }
          }
        },
        {
          "weight": 1.0,
          "filter": {
            "geo_distance_range": {
              "location": "43.653473, -79.388692",
              "from": 20.0,
              "to": 1000.0,
              "unit": "km"
            }
          }
        }
      ],
      "filter": {
        "geo_distance": {
          "location": "43.653473, -79.388692",
          "distance": 50.0,
          "unit": "km"
        }
      },
      "random_score": {}
    }
  }
```
I am getting this error:

org.elasticsearch.ElasticsearchParseException: You can either define "functions":[...] or a single function, not both. Found "functions": [...] already, now encountering "random_score".

I guess this isn't possible right now as the random score has to go inside the functions clause like in the example.   Which works when I fix up the query output manually and run it against elasticsearch.

**Comment by gmarz** [comment]
Yea, it looks like [FunctionScoreFunctionsDescriptor](https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/Query/Functions/FunctionScoreFunctionsDescriptor.cs) is missing RandomScore.  We'll add this for the next release, thanks for reporting!

**Comment by richardwhatever** [comment]
Hi @gmarz, is this still in the next release? Any ETA?  Many thanks.

**Comment by gmarz** [comment]
Hey @richardwhatever 

Apologies, NEST 2.0 is the priority right now and we haven't had many cycles to work on a 1.7.2 release- but yes, it is still planned and we'll try to get it out asap.

**Comment by richardwhatever** [comment]
Awesome - many thanks!

On 10 November 2015 at 13:48, Greg Marzouka <notifications@github.com>
wrote:

> Hey @richardwhatever <https://github.com/richardwhatever>
>
> Apologies, NEST 2.0 is the priority right now and we haven't had many
> cycles to work on a 1.7.2 release- but yes, it is still planned and we'll
> try to get it out asap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-net/issues/1559#issuecomment-155424071>
> .
>



-- 
*Richard Brown*
@richardwhatever
uk.linkedin.com/in/richardbrownni

**Comment by gmarz** [comment]
@russcam The fix looks good, but it's controversial.  The functions at the query root is definitely wrong, but removing them from the interface technically breaks semver compatibility.  Do we make an exception in this case?  We haven't done so in the past.  As much as I hate doing this, we may need to leave them on the interface and mark as obsolete with a message.  I can easily be convinced otherwise though... :).  Thoughts?

/cc @Mpdreamz

**Comment by Mpdreamz** [comment]
Definitely add them back, we need to stay binary compatible since we do not update our assembly version on our signed dlls (just assemlyfileversion). 

Obsolete maybe with error = true to cause compilation errors explaining the problem.

**Comment by gmarz** [comment]
+1 error = true

**Comment by russcam** [comment]
Obsolete with error is a good compromise to maintaining compatibility - the OCD me **so** wants to remove them but I'd rather not upset a swathe of users ;)

Will add them back in now.

**Comment by russcam** [comment]
Added back in https://github.com/elastic/elasticsearch-net/commit/1cd841b02942f17538077931862c37e67cbd5edd. Since calling a method marked `Obsolete` with error=true is a compiler error, I removed the method implementations on the descriptor.
